######################## default configuration ####################
baseURL = "https://blog.tristangoetz.me"
title = "Blog - TRG"
theme = "nebula"
languageName = "En"
languageCode = "en-us"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

############################# output ##############################
[outputs]
home = [ "HTML", "RSS"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"


################################ menu ##################################
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

#[[menu.main]]
#name = "Privacy Policy"
#URL = "privacy-policy"
#weight = 4


#################### default parameters ################################
[params]
# Meta data
description = "Christian, Husband, Father, Coder, Disc Golfer"
author = "Tristan Goetz"
# sidebar portrait
portrait = "images/author.jpg"
# sidebar bio
bio = "Christian, Husband, Father, Coder, Disc Golfer"
# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.


############################# social site ########################
# themify icons : https://themify.me/themify-icons

[[params.social]]
title = "facebook"
icon = "ti-facebook"
link = "https://www.facebook.com/tristan.r.goetz"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "https://twitter.com/TGoetzDiscGolf"

[[params.social]]
title = "instagram"
icon = "ti-instagram"
link = "https://www.instagram.com/tristangoetzdiscgolf/"

[[params.social]]
title = "github"
icon = "ti-github"
link = "https://github.com/SpyderHunter03"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/tristan-goetz/"