# baseURL = 'http://blog.tristangoetz.me/'
# languageCode = 'en-us'
# title = 'Tristan Goetz Blog'
# theme = 'ananke'

baseURL = 'http://blog.tristangoetz.me/'
languageCode = 'en-us'

# website title
title = 'Tristan Goetz Blog'

# theme
theme = "NewBee"

# i18n
defaultContentLanguage = "en-us"
defaultContentLanguageInSubdir = false

# whether to use robots.txt
enableRobotsTXT = true

# whether to use git info
enableGitInfo = true

# length of summary
summaryLength = 50

hasCJKLanguage = true

[author]
    name = "Tristan Goetz"
    description = "Full-Stack Developer.  Full-Stack Friend."

    # profile photo of author in author card
    image = "/images/author.jpeg"

    # link of follow me in author card and footer
    link = "https://github.com/spyderhunter03"

# Taxonomies
[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[params]

    # page configuration
    [params.page]

        # top image in home page, note that the "/" in path is necessary, the same applies below
        homeTopImg = "/images/home.jpg"

        # title in home top image, support Markdown
        homeTitle = "Tristan Goetz"

        # font size(px)
        homeTitleFontSize = 40

        # content in home top image, support Markdown
        homeContent = "Full-Stack Developer.  Full-Stack Friend."

        # font size(px)
        homeContentFontSize = 20

        # top image in categories terms page
        categoryTopImg = "/images/categories.jpg"
        # description of categories terms page
        categoryDes = "description of categories page"

        # top image in series terms page
        seriesTopImg = "/images/series.jpg"
        # description of series terms page
        seriesDes = "description of series page"

        # top image in tags terms page
        tagTopImg = "/images/tag.jpg"
        # description of tags terms page
        tagDes = "description of tags page"

        # top image in archives(posts) page
        archivesTopImg = "/images/archive.jpg"
        # description of archives(posts) page
        archivesDes = "description of archives(posts) page"

        # top image in about page
        aboutTopImg = "/images/about.jpg"
        # description of about page
        aboutDes = "description of about page"

        # default image for a post without "image" param
        postsTopImg = "/images/default.jpg"
        
        maxHomePostCount = 5
        maxPageRelatedCount = 5
        maxPageNewestCount = 5

    # Valine comment：https://valine.js.org/
    [params.valine]
        enable = false
        # appid：https://valine.js.org/configuration.html#appId
        appid = 'sPMvdUAhmPSPXV6UDU5ojUn2-gzGzoHsz'
        # appKey：https://valine.js.org/configuration.html#appKey
        appkey = '8OdwR8bCYGbH8BSwOSfBzKVK'
        placeholder = 'placeholder'
        avatar = 'robohash'
        requiredFields = ['nick']
        visitor = true
        pageSize = 5

    # footer
    [params.footer]
        enable = true
        copyRight = true
        from = 2022
        # whether to enable count of visitor and view
        visitor = false
        # whether to enable theme information
        themeInfo = false

    # aplayer, se  more: https://aplayer.js.org
    [params.aplayer]
        enable = false
        server = "netease"
        type = "playlist"
        id = 752439587
        fixed = true
        autoplay = false
        loop = "all"
        order = "random"
        preload = "auto"
        list_folded = "ture"
        list_max_height = "500px"
        lrc_type = 1

[menus]
    # navigation entries
    [[menus.main]]
        name = "Home"
        url = "/"
        # order weight, more small more close to left, at least 1
        weight = 1
        # icon from FontAwesome in front of single entry
        pre = "<i class='fa fa-home'></i>"
    [[menus.main]]
        name = "Posts"
        url = "/posts"
        weight = 2
        pre = "<i class='fa fa-book'></i>"
    [[menus.main]]
        name = "Categories"
        url = "/categories"
        weight = 3
        pre = "<i class='fa fa-folder-open'></i>"
    [[menus.main]]
        name = "Series"
        url = "/series"
        weight = 4
        pre = "<i class='fa fa-gears'></i>"
    [[menus.main]]
        name = "Tags"
        url = "/tags"
        weight = 5
        pre = "<i class='fa fa-tags'></i>"
    [[menus.main]]
        name = "About"
        url = "/about"
        weight = 6
        pre = "<i class='fa fa-info-circle'></i>"

    # social entries
    [[menus.social]]
        name = "GitHub"
        url = "https://github.com/spyderhunter03"
        pre = "<i class='fa fa-github'></i>"
        weight = 1
    [[menus.social]]
        name = "YouTube"
        url = "https://www.youtube.com/spyderhunter03"
        pre = "<i class='fa fa-youtube'></i>"
        weight = 2

    # sponsor entries, not more than 3
    # [[menus.appreciate]]
    #    name = "Wechat"
    #    url = "/images/appreciate/Wechat.jpeg"
    # [[menus.appreciate]]

# [permalinks]
#     posts = '/:year/:month/:title/'


# related configuration, see more: https://gohugo.io/content-management/related/
[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100
        toLower = false

    [[related.indices]]
        name = "tags"
        weight = 80
        toLower = false

    [[related.indices]]
        name = "date"
        weight = 10

# Markup related configuration in Hugo
[markup]
    # syntax highlight, see more: https://gohugo.io/functions/highlight/
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        lineNos = true
        anchorLineNos = false
        lineNumbersInTable = true
        noClasses = false
        noHl = false
        # https://xyproto.github.io/splash/docs/
        style = 'monokailight'
        tabWidth = 4

    # enable the following code if there are html statements in your md file
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true